run:
  issues-exit-code: 1
  tests: true
linters:
  disable:
    - errcheck
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - staticcheck
    - unused
    - whitespace
linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
issues:
  exclude-use-default: false
  exclude:
    - 'shadow: declaration of "err" shadows declaration at line (\d+)'
  max-issues-per-linter: 0
  max-same-issues: 0
